on:
  workflow_dispatch:
  workflow_call:
    secrets:
      APP_ID:
        required: true
      APP_PEM:
        required: true

env:
  TARGET_REPO_PATH: test-repo-1
  AUTOMATION_REPO_PATH: test-repo-automation

jobs:
  update-content:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout automation repository
        uses: actions/checkout@v4
        with:
          ref: main
      - name: Make changes to target repository
        id: make_changes
        run: |
          date +%s > report.txt
      - name: Save changes to artifact
        uses: actions/upload-artifact@v4
        with:
          name: changes
          path: ./report.txt

  create-pull-request:
    needs: [ update-content ]
    runs-on: ubuntu-latest
    steps:
      - name: Checkout target repository
        uses: actions/checkout@v4
        with:
          ref: test-stable-branch-1
          fetch-depth: 0
          repository: ray-test-organzation/${{ env.TARGET_REPO_PATH }}  # not the automation repo
      - name: Download changes to current repository
        uses: actions/download-artifact@v4
        with:
          name: changes
          path: ./report.txt
      - uses: actions/create-github-app-token@v1
        id: app-token
        with:
          app-id: ${{ secrets.APP_ID }}
          private-key: ${{ secrets.APP_PEM }}
          owner: ray-test-organzation
          repositories: "${{ env.TARGET_REPO_PATH }}"
      - name: Create pull request
        uses: canonical/create-pull-request@main
        with:
          github-token: ${{ steps.app-token.outputs.token }}
          commit-message: Test commit message
          branch-name: test-release-branch-1
          title: Test pull request
          base: test-stable-branch-1
          body: Test pull request body
          upsert: true
          repository: "ray-test-organzation/${{ env.TARGET_REPO_PATH }}"
