on:
  workflow_dispatch:
  workflow_call:
    secrets:
      APP_ID:
        required: true
      APP_PEM:
        required: true

env:
  TARGET_REPO_PATH: test-repo-1
  AUTOMATION_REPO_PATH: test-repo-automation

jobs:
  update-snapcraft:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout target repository
        uses: actions/checkout@v4
        with:
          ref: main
          path: ${{ env.TARGET_REPO_PATH }}
          repository: ray-test-organzation/${{ env.TARGET_REPO_PATH }}  # not the automation repo
      - name: Checkout automation repository
        uses: actions/checkout@v4
        with:
          ref: main
          path: ${{ env.AUTOMATION_REPO_PATH }}
      - name: Install tox
        run: |
          sudo apt-get update
          sudo apt-get install --yes tox
      - name: Make changes to target repository
        id: make_changes
        working-directory: ${{ env.TARGET_REPO_PATH }}
        run: |
          date +%s > report.txt
      - uses: actions/create-github-app-token@v1
        id: app-token
        with:
          app-id: ${{ secrets.APP_ID }}
          private-key: ${{ secrets.APP_PEM }}
          owner: ray-test-organzation
          repositories: "test-repo-1"
      - name: Commit changes to target repository
        id: commit_changes
        working-directory: ${{ env.TARGET_REPO_PATH }}
        env:
          GITHUB_TOKEN: ${{ steps.app-token.outputs.token }}  # use github app token
          FILE_TO_COMMIT: report.txt
          DESTINATION_BRANCH: chore/automation
        run: |
          export MESSAGE="update content"
          export SHA=$( git rev-parse $DESTINATION_BRANCH:$FILE_TO_COMMIT )
          export CONTENT=$( base64 -i $FILE_TO_COMMIT )
          git branch $DESTINATION_BRANCH
          gh api --method PUT /repos/ray-test-organzation/test-repo-1/contents/$FILE_TO_COMMIT \
            --field message="$MESSAGE" \
            --field content="$CONTENT" \
            --field encoding="base64" \
            --field branch="$DESTINATION_BRANCH" \
            --field sha="$SHA"
      - name: Create Pull Request
        id: create_pr
        working-directory: ${{ env.TARGET_REPO_PATH }}
        env:
          GITHUB_TOKEN: ${{ steps.app-token.outputs.token }}  # use github app token
          HEAD_BRANCH: chore/automation
          BASE_BRANCH: main
          PR_TITLE: "Update README.md"
          PR_MESSAGE: "Automated changes create by https://github.com/ray-test-organzation/test-repo-automation/blob/main/.github/workflows/create-pull-request.yaml"
        run: |
          gh pr create \
            --head ${{ env.HEAD_BRANCH }} \
            --base ${{ env.BASE_BRANCH }} \
            --title ${{ env.PR_TITLE }} \
            --body ${{ env.PR_MESSAGE }} \
